language: node_js
node_js:
  - '0.10'

before_install: npm install -g grunt-cli
install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install
before_script: grunt build
script: karma start karma-travis.conf.js
